name: Node CI Suite

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Node Tests

    strategy:
      matrix:
        node-version: [22.x, 24.x]
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm test
